language: node_js
node_js:
- '6'
before_script:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: ui-admin.e@klarna.com
  api_key:
    secure: ISBBc4doE7FYdvx/XcJiL6Mg+6AfpExDzDqi6SsNS3ZyyE2oYOQtBWfw9z5Z1s8xUPAJ6CUNUfi7HElXQfXwvaSgzoh/dlANbbuEhnYQ+LTOyb1jy1u5WG90cgy5fVaBJ2mLAQjdlicccMRpZQ/Wgu/RX5Q26UfAC+KL6Y0/8Y3Hblz9voeRR5afkMGa5MVe814moxjgO1DzS1Dpx8PTiKZOyS6UFB/+CZbEq8ewo40geUKNsVXYP1m1aOOQFSaK9oM1GwQopV4U2h9CmarynTVK/jpLYT9JCdQOUVWey2FV3iqi/pGTDCu7+Aalw6Hhu19VlrEk5Qh76bKwzrc5pzcRYt9VC4qKZFg006jPw56aZqrftsC/E8PLmAGe0edR5pwUdQ8kXl8bzhBTA6MOiwdON6/obqwSVsqNZmnIGc/azmhautPmCSCGnHk/DE0kfQAdhS2KFTq6IRrvjH+AFUDT7O9Ix+MEArpqVDzcpUxf6Etntp+pfeWN/NA7xuaxtY3t6T9nj1iu1fOqNsn6FkOwoSnuCip0Ptu4gkAk62hwDx1xNmFW10O/WTPbtuQuA/FPMYv4oYjcsmbGiMz6lLwmXPlS0equHY0t/udBR3LRsdG9f7IQf6TWGMlS/AhOwJziW2oq9yQFfjW8v3HWZKCsPw84yEhzcXUPi75e6OU=
  on:
    tags: true
    repo: klarna/higher-order-components
