language: node_js
node_js:
- '6'
before_script:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: ui-admin.e@klarna.com
  api_key:
    secure: TRN+rL+yoM7krH2eMAiZ65V1ztG+3XpOGABP2O66oX0knzOV4numL31yhuXplQW7pPMjxDr7Xk8v5OPif2QWJ/gE/AOoqxU8fTf/g+34HTRjnm6E6me1XYfE4KQRdCupA0iIK7sJ1WmZGg6ze5JOA2xLvkTnsCgu4JlPnAF/+cDkGWUxFHlUiUJ4t1WZnc52T4Rm2sNaFW6CfsHHIFW+pueeCJcrwFqFXgyp7JFDS1xD/4TVPo72LD5w3g3FtLcizXu2+GmmVbmzEnppaWOtqZr61nnPH22C0myD0O4vlf9PiJCd+Xng3upG6fbNu0hfsyFyy154iJm3f03rhqy/LDgzoCtSZZkeb4U+GOIIuPPXgGemHqVke7cLfYpWv+xhgWdtSZfNHejfCc8cgBbl4Gki25nSifYm4baCfq1gZlws4cMX1VE8of04BtaMEMZesnN1Ooz5ze724bFumODgJnuuryNLu5lCNGjGlc4oyxzwo7mPFejJ8cVAmK+/HLoprS7kwHmlogHv+IUSiUxgK3LwxDqlM8x0ijqPYcpO+LoUZfSujV301kO+xHoPspwVlpgdY0QFMeIWjh+lNJ2JADK5P00i6BdjKPbdxaqvwx57lWzSHePrRsa5BlEZmOV5M8jlTFw+YDNo7qjbOglraSw+8ZfglwjWtysUyH0wPXo=
  on:
    tags: true
    repo: klarna/higher-order-components
