language: node_js
node_js:
- '6'
before_script:
- npm install
script:
- npm test
deploy:
  skip_cleanup: true
  provider: npm
  email: ui-admin.e@klarna.com
  api_key:
    secure: DQFt2IcwLVz7IN1SuUtfkerDJz9ePPyHsSBGjHAWb1FmS2bSaBbc06SMkXKXACv2oAwk/iviZF9DXeGScn5z8J+6ewtbxRxIVgeOJN4tjwX7V4J/2TM8gEmWAfwYj3VO+eFqpobQJZJUcF3pchE1w9O0F7e2iOjQTFPhVvOc66lHyBCpeJqs5BZkEmg1OyYrF3/GKOHmy7ZhCbNkbgvGNceeFH7VDk8DdhqX3VzE5f5Okc7AnRv2N64pti5t0K0kq0+3iED4HuzhY1UkKeBaUjSl4on+QVuAZdROY6+SCeWMcJrmBIw2CxjoHeTdwPsIfYcqrZJx+E5MPWQupu4WZ2W+nc55QwpaAyM4TLncIVVY8AtQH6doy57mc5nwC4HxH5o4SEwXmWR8XllWlr9EsQfT2gVTYT1a7gr5ASTh9ZO9jq+XFonC2M/QW08UHQncjNHunvW85OcB0k/I011q8Vlv2VT/5GpRY27FuiRo/mgNVQYkPlntIdM8H3Bi499ii5XgA+STAoSH42iOgEH10aVGY7RfA9n4MYFTzVq4bUSkoWA/SnLEeCEoU3vF3tc1nPWSuBqX8SqDs6ACNkDIfqj41vveQTRF5K0d29PoabtrorxLZF4BMYAWZTP1nfIwcmiYzDZ0J3R5q/D3LX2GARKYGrK9bVEX48ybdQUTpok=
  on:
    tags: true
    repo: klarna/higher-order-components
